require "time"
require "fileutils"
require "rubygems"
require "cucumber"
require "cucumber/rake/task"
require "json"

task :specs, [:tags, :browser] do |task, args|
  time = Time.now.utc.iso8601.tr(":", "")
  report = "--format html  --out=log/report_#{time}.html"
  sh "cucumber  #{args[:tags]} #{report} #{args[:browser]}"
end
